apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello2-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: 
    metadata:
      labels:
        app: hello2
    spec:
      containers:
      - name: hello2
        image: darkmagician/hellonode
        ports:
        - containerPort: 8080
        
---
kind: Service
apiVersion: v1
metadata:
  name: hello2
spec:
  selector:
    app: hello2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
