apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello3-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: 
    metadata:
      labels:
        app: hello3
    spec:
      containers:
      - name: hello3
        image: darkmagician/hellonode
        ports:
        - containerPort: 8080
       
---
kind: Service
apiVersion: v1
metadata:
  name: hello3
spec:
  selector:
    app: hello3
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080