apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simplenode-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: 
    metadata:
      labels:
        app: simplenode
    spec:
      containers:
      - name: simplenode
        image: darkmagician/simplenode
        ports:
        - containerPort: 8080